-- liquibase formatted sql
-- changeset serathiuk:000000000003
CREATE TABLE VENDA (
  ID VARCHAR(100) NOT NULL,
  ID_FILIAL VARCHAR(100) NOT NULL,
  ID_PESSOA VARCHAR(100) NOT NULL,
  VALOR_VENDA DECIMAL(15,2) NOT NULL,
  STATUS_OPERACAO VARCHAR(32) NOT NULL
);
ALTER TABLE VENDA ADD CONSTRAINT VENDA_PK PRIMARY KEY(ID);
ALTER TABLE VENDA ADD CONSTRAINT VENDA_FK1 FOREIGN KEY (ID_FILIAL) REFERENCES FILIAIS(ID);
ALTER TABLE VENDA ADD CONSTRAINT VENDA_FK2 FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS(ID);