spring:
  datasource:
    url: ${DATABASE_JDBC_URL}
    username: ${DATABASE_LOGIN}
    password: ${DATABASE_PASSWORD}          

server:
  port: 5000
  
serathiukerp:
  sqs:
    endpoint: ${SQS_ENDPOINT}
  integracaobancaria:
    endpoint: ${INTEGRACAO_BANCARIA_ENDPOINT:}
  sns:
    arn: ${ARN_SNS}