-- liquibase formatted sql
-- changeset serathiuk:000000000003
CREATE TABLE ORDEM_PAGAMENTO (
      ID VARCHAR(100) NOT NULL,
      ID_PAGAR_RECEBER VARCHAR(100) NOT NULL,
      ID_CONTA_BANCARIA VARCHAR(100) NOT NULL,
      ID_FILIAL_PAGAMENTO VARCHAR(100) NOT NULL,
      VALOR_TOTAL DECIMAL(15,2) NOT NULL,
      STATUS VARCHAR(32) NOT NULL
);
ALTER TABLE ORDEM_PAGAMENTO ADD CONSTRAINT ORDEM_PAGAMENTO_PK PRIMARY KEY(ID);
ALTER TABLE ORDEM_PAGAMENTO ADD CONSTRAINT ORDEM_PAGAMENTO_FK1 FOREIGN KEY (ID_PAGAR_RECEBER) REFERENCES PAGAR_RECEBER(ID);
ALTER TABLE ORDEM_PAGAMENTO ADD CONSTRAINT ORDEM_PAGAMENTO_FK2 FOREIGN KEY (ID_CONTA_BANCARIA) REFERENCES CONTAS_BANCARIAS(ID);

CREATE TABLE ORDEM_RECEBIMENTO (
      ID VARCHAR(100) NOT NULL,
      ID_PAGAR_RECEBER VARCHAR(100) NOT NULL,
      ID_CONTA_BANCARIA VARCHAR(100) NOT NULL,
      ID_FILIAL_PAGAMENTO VARCHAR(100) NOT NULL,
      VALOR_TOTAL DECIMAL(15,2) NOT NULL,
      STATUS VARCHAR(32) NOT NULL
);
ALTER TABLE ORDEM_RECEBIMENTO ADD CONSTRAINT ORDEM_RECEBIMENTO_PK PRIMARY KEY(ID);
ALTER TABLE ORDEM_RECEBIMENTO ADD CONSTRAINT ORDEM_RECEBIMENTO_FK1 FOREIGN KEY (ID_PAGAR_RECEBER) REFERENCES PAGAR_RECEBER(ID);
ALTER TABLE ORDEM_RECEBIMENTO ADD CONSTRAINT ORDEM_RECEBIMENTO_FK2 FOREIGN KEY (ID_CONTA_BANCARIA) REFERENCES CONTAS_BANCARIAS(ID);
