-- liquibase formatted sql
-- changeset serathiuk:000000000002
ALTER TABLE LANCAMENTOS_FLUXO_CAIXA ADD DESCRICAO_LANCAMENTO VARCHAR(200);
ALTER TABLE BAIXAS_PAGAR_RECEBER ADD OBSERVACOES VARCHAR(200);