spring:
  datasource:
    url: ${DATABASE_JDBC_URL:jdbc:postgresql://localhost:5432/pocerp_integracaobancaria}
    username: ${DATABASE_LOGIN:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  devtools:
    restart:
      enabled: false   

server:
  port: 5003