-- liquibase formatted sql
-- changeset serathiuk:000000000001
CREATE TABLE PAGAMENTOS (
	NSU BIGINT NOT NULL,
	IDENTIFICADOR VARCHAR(100) NOT NULL,
	STATUS VARCHAR(32) NOT NULL,
	VALOR_DOCUMENTO DECIMAL(15,2) NOT NULL
);

ALTER TABLE PAGAMENTOS ADD CONSTRAINT PAGAMENTOS_PK PRIMARY KEY(NSU);

CREATE SEQUENCE PAGAMENTOS_SEQ START 1;

CREATE TABLE RECEBIMENTOS (
	NSU BIGINT NOT NULL,
	IDENTIFICADOR VARCHAR(100) NOT NULL,
	STATUS VARCHAR(32) NOT NULL,
	VALOR_DOCUMENTO DECIMAL(15,2) NOT NULL
);

ALTER TABLE RECEBIMENTOS ADD CONSTRAINT RECEBIMENTOS_PK PRIMARY KEY(NSU);

CREATE SEQUENCE RECEBIMENTOS_SEQ START 1;
